#!/usr/bin/env bash

cd dist
git pull $1 master
git rm -r *
rm -rf *
cd ../
rsync -av ./ dist --exclude dist/ --exclude .git/ --exclude .gitignore --exclude .glitch-assets --exclude node_modules/ --exclude .env --exclude deploy --exclude README.md --exclude test/ --exclude logs/

if [[ `git status --porcelain` ]]; then
  git add -A .
  git commit -m "Deploy"
else
  echo "no changes"
fi;
git push $1 master